### ISSUE TITLE
Is this package still relevant since scout has built-in support for meilisearch index settings ?

### ISSUE THREAD

**Issue by smknstd** [dwarfhq/laravel-meilitools#6]
https://github.com/laravel/scout/releases/tag/v9.5.0
https://laravel.com/docs/9.x/scout#configuring-filterable-data-for-meilisearch

**Comment by FrittenKeeZ** [comment]
The short answer is "yes", this package is this relevant, as it's not depending on using Scout and offers additional utilities for MeiliSearch, but it's nice to see built-in handling of index settings.

**Comment by smknstd** [comment]
Great ! Maybe you should mention this in the readme.
